require('yaya.options')
require('yaya.keymaps')
require('yaya.plugins')
require('yaya.colorscheme')
require('yaya.cmp')
require('yaya.lsp')
require('yaya.telescope')
require('yaya.treesitter')
require('yaya.autopairs')
-- require('yaya.comment')
require('yaya.gitsigns')
require('yaya.nvim-tree')
require('yaya.bufferline')
require('yaya.null-ls')
require('yaya.lualine')
require('yaya.toggleterm')
require('yaya.project')
require('yaya.impatient')
require('yaya.indentline')
require('yaya.alpha')
-- require('yaya.whichkey')
require('yaya.autocommands')
-- require'lspconfig'.tsserver.setup{}
