#!/bin/sh

#nvim
NVIM=~/.config/nvim
if [ -d "$NVIM" ]; then
	mv ~/.config/nvim ~/.config/nvim-bbac
fi
ln -sv ~/Projects/dotfiles/nvim ~/.config/nvim

#scripts
SCRIPTS=~/.local/scripts
if [ -d "$SCRIPTS" ]; then
	mv ~/.local/scripts ~/.local/scripts-bbac
fi
ln -sv ~/Projects/dotfiles/scripts ~/.local/scripts

#i3
I3=~/.config/i3
if [ -d "$SCRIPTS" ]; then
	mv ~/.config/i3 ~/.config/i3-bbac
fi
ln -sv ~/Projects/dotfiles/i3 ~/.config/i3
