require "baky.options"
require "baky.plugins"
require "baky.colorscheme"
require "baky.keymapping"
require "baky.cmp"
require "baky.lsp"
require "baky.telescope"
require "baky.treesitter"
require "baky.autopairs"
require "baky.comment"
require "baky.gitsigns"
require "baky.nvim-tree"
require "baky.bufferline"
require "baky.lualine"
require "baky.toggleterm"
require "baky.project"
require "baky.impatient"
require "baky.indentline"
require "baky.alpha"

vim.cmd [[set colorcolumn=80]] -- n -- TODO: this doesn't seem to work
