#!/bin/sh
echo 'How process you want to kill?'
read process
kill $(ps aux | grep $process | awk 'NR == 1 {print $2}')
while [ $? -eq 0 ]; do
	kill $(ps aux | grep $process | awk 'NR == 1 {print $2}')
done
