#!/bin/sh
US='us(dvorak-intl)'
BR='br(dvorak-intl)'

currentKeyboardLayout=$(setxkbmap -print | awk -F"+" '/xkb_symbols/ {print $2}'
)

if [[ $currentKeyboardLayout == $US ]]; then
	setxkbmap $BR
else
	setxkbmap $US
fi
