#!/bin/sh

arg=$1
is_valid_arg=false

declare -a options
options=(trybe java me)

print_msg_error() {
  echo "Choose a folder"
  echo "trybe:  Trybe projects"
  echo "me:     Me projects"
  echo "java:   Java projects"
}

check_exist_arg() {
  param1=$1
  if [[ -z "$param1" ]]; then
    print_msg_error
    exit
 fi
}

check_valid_arg() {
  param1=$1
  param2=("${!2}")

  for option in ${param2[@]};
  do
    if [[ "$param1" == $option ]]; then
      is_valid_arg=true
    fi
  done
}

get_folder() {
  param1=$1
  if [[ "$param1" == "trybe" ]]; then
    projects=~/01-trybe/projects
  fi

  if [[ "$param1" == "java" ]]; then
    projects=~/01-trybe/acc-projects
  fi

  if [[ "$param1" == "me" ]]; then
    projects=~/02-me/projects
  fi
}

print_options() {
  param1=$1
  declare -a array
  i=0

  cd $(echo $param1)

  for list in *;
    do
      array[$i]=$list
      echo $i '=>' ${array[$i]}
      ((i++))
    done

  read -n2 selected

  if [[ "$selected" == 0 ]]; then
    cd $(echo $param1)
    cd $(ls)
    clear
    exec zsh
  fi  


  cd $(echo $param1/${array[$selected]})
  cd $(ls)
  clear
  exec zsh
}

check_exist_arg $1
check_valid_arg $arg options[@]

if [[ "$is_valid_arg" == true ]]; then
  get_folder $arg
  print_options $projects
else
  print_msg_error
fi  
